name: Backend CI/CD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@master
    
    - name: Set up JDK 1.13
      uses: actions/setup-java@v1
      with:
        java-version: 1.13
    
    - name: Build
      run: mvn clean package spring-boot:repackage

    - name: Publish version
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: uladzimirbaklan/lecturer-private-cabinet-backend:latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true
